# Generated by Django 3.2.14 on 2022-07-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_app', '0001_create_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casting_app.company'),
        ),
    ]
