# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Validate_and_Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-pip-${{ hashFiles('py-requirements/*.txt') }}

    - name: Set-up Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate static
      run: |
        black --skip-string-normalization --line-length 120 --check casting_app
        isort --atomic --profile black -c casting_app
        bandit -r casting_app
    
    - name: Run tests
      run: |
        export SECRET_KEY='django-insecure-m^q+w19@p^zrqoi_twi2^95@9$&fw!m6y684ax8@a@!#4syn!e'
        python manage.py migrate
        python manage.py test
